/* NEXMIR V5.0.14 · sesiones breves, registro de errores y reportes editoriales */
(() => {
  const key=q=>`${q._source||'questions'}:${q.id}`;
  const findQuestion=k=>questionPool().find(q=>key(q)===k);
  const logFor=q=>state.errorLog.find(e=>e.source_type===(q._source||'questions')&&e.source_id===String(q.id));
  const reasonLabels={pending:'Sin clasificar',knowledge:'No conocía el concepto',interpretation:'Interpreté mal el caso',memory:'Olvidé un dato',time:'Me faltó tiempo',doubt:'Dudé entre opciones',other:'Otro motivo'};
  const stamp=s=>s?new Date(s).toLocaleDateString('es-ES'):'—';
  const validDate=s=>/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s));
  const currentQuestion=()=>state.bank?.pool?.[state.bank.index];
  const reportButton=q=>q?`<button type="button" class="btn mini" onclick="openQuestionReport('${key(q)}')">⚑ Reportar contenido</button>${state.profile?.role==='admin'?`<button type="button" class="btn mini danger admin-delete-question" data-question-key="${key(q)}" onclick="deleteQuestionAsAdmin('${key(q)}')">Eliminar pregunta</button>`:''}`:'';
  function buttonNear(container,q){if(container&&!container.querySelector('.report-content-action'))container.insertAdjacentHTML('beforeend',`<div class="report-content-action">${reportButton(q)}</div>`)}

  const oldShowQuestion=showQuestion;
  showQuestion=function(){oldShowQuestion();const q=currentQuestion();buttonNear($('#questionDialogBody .bank-nav-actions'),q);if(state.bank.answered&&state.bank.mode==='immediate')buttonNear($('#qFeedback .card'),q)};
  const oldBankReview=renderBankReviewQuestion;
  renderBankReviewQuestion=function(i){oldBankReview(i);const q=state.bank.pool[i];buttonNear($('#bankReviewDetail'),q);if(q)$('#bankReviewDetail .report-content-action')?.insertAdjacentHTML('beforeend',` <button class="btn mini" onclick="markQuestionDoubt('${key(q)}')">Marcar como dudosa</button>`)};
  const oldSimulationQuestion=renderSimulationQuestion;
  renderSimulationQuestion=function(){oldSimulationQuestion();buttonNear($('#simDialogBody .sim-bottom'),state.simulation?.pool?.[state.simulation.index])};
  const oldSimulationReview=renderSimulationReviewQuestion;
  renderSimulationReviewQuestion=function(i){oldSimulationReview(i);const q=state.simulation?.pool?.[i];buttonNear($('#simReviewDetail'),q);if(q)$('#simReviewDetail .report-content-action')?.insertAdjacentHTML('beforeend',` <button class="btn mini" onclick="markQuestionDoubt('${key(q)}')">Marcar como dudosa</button>`)};

  function openQuestionReport(k){const q=findQuestion(k);if(!q)return toast('Pregunta no disponible');const d=$('#reportDialog');d.dataset.key=k;$('#reportQuestion').textContent=reviewQuestionPreview(q,240);$('#reportPart').value='question';$('#reportCategory').value='incorrect';$('#reportDetail').value='';$('#reportMessage').textContent='';d.showModal()}
  async function submitQuestionReport(){const d=$('#reportDialog'),q=findQuestion(d.dataset.key),detail=$('#reportDetail').value.trim(),btn=$('#submitReportBtn');if(!q)return toast('Pregunta no disponible');if(detail.length<10||detail.length>2000){$('#reportMessage').textContent='Describe el problema en 10 a 2000 caracteres.';return}btn.disabled=true;const {error}=await state.sb.from('question_reports').insert({user_id:state.user.id,source_type:q._source||'questions',source_id:String(q.id),part:$('#reportPart').value,category:$('#reportCategory').value,detail});btn.disabled=false;if(error){$('#reportMessage').textContent='No se pudo enviar: '+error.message;return}d.close();toast('Reporte enviado a revisión. Gracias.')}
  $('#submitReportBtn').addEventListener('click',submitQuestionReport);

  function errorRows(){const m=new Map();for(const e of state.errorLog){const q=findQuestion(`${e.source_type}:${e.source_id}`);if(q)m.set(key(q),{q,e})}for(const a of state.attempts.filter(a=>a.is_valid!==false&&a.is_correct===false)){const q=getAttemptQuestion(a);if(q&&!m.has(key(q)))m.set(key(q),{q,e:{source_type:q._source,source_id:String(q.id),reason:'pending',failures:1,last_error_at:a.answered_at,next_review_at:new Date(new Date(a.answered_at).getTime()+86400000).toISOString()}})}return [...m.values()].sort((a,b)=>new Date(a.e.next_review_at)-new Date(b.e.next_review_at))}
  function renderErrorLog(){const rows=errorRows();$('#view-errors').innerHTML=`<div class="section-head"><div><h2>Registro de errores y dudas</h2><p class="muted">Clasifica por qué fallaste, elige el próximo repaso y vuelve a resolver la pregunta.</p></div><span class="chip">${rows.length} preguntas</span></div><div class="list">${rows.map(({q,e})=>`<div class="card error-entry"><div class="row"><div class="grow"><strong>${mdInline(q.stem||q.question||'Pregunta')}</strong><div class="path">${esc([q.specialty,q.topic].filter(Boolean).join(' › '))} · ${e.failures||0} fallos${e.uncertain?' · Dudosa':''}</div></div><span class="chip">${new Date(e.next_review_at).getTime()<=Date.now()?'Repasar hoy':'Repaso '+stamp(e.next_review_at)}</span></div><div class="grid cols-3 error-controls"><label>Motivo<select id="reason_${key(q)}">${Object.entries(reasonLabels).map(([v,label])=>`<option value="${v}" ${e.reason===v?'selected':''}>${label}</option>`).join('')}</select></label><label>Fecha de repaso<input id="date_${key(q)}" type="date" value="${(e.next_review_at||'').slice(0,10)}"></label><label>Nota personal<input id="note_${key(q)}" maxlength="1000" value="${esc(e.note||'')}" placeholder="¿Qué debo recordar?"></label></div><div class="dialog-actions"><button class="btn mini primary" onclick="saveErrorEntry('${key(q)}')">Guardar</button><button class="btn mini" onclick="reviewErrorQuestion('${key(q)}')">Resolver de nuevo</button><button class="btn mini" onclick="studyRelated('${encodeURIComponent(q.specialty||'')}','${encodeURIComponent(q.topic||'')}')">Ver tema</button>${reportButton(q)}</div></div>`).join('')||'<div class="empty">Tus fallos se guardarán aquí al responder preguntas. También puedes marcar una pregunta como dudosa.</div>'}</div>`}
  renderErrors=renderErrorLog;
  async function saveErrorEntry(k){const q=findQuestion(k),e=q&&logFor(q),reason=document.getElementById(`reason_${k}`)?.value,note=document.getElementById(`note_${k}`)?.value.trim()||'',date=document.getElementById(`date_${k}`)?.value;if(!q||!validDate(date))return toast('Elige una fecha de repaso válida');const payload={reason,note,next_review_at:new Date(`${date}T12:00:00`).toISOString(),updated_at:new Date().toISOString()};const res=e?await state.sb.from('user_error_log').update(payload).eq('id',e.id).eq('user_id',state.user.id).select().single():await state.sb.from('user_error_log').insert({...payload,user_id:state.user.id,source_type:q._source,source_id:String(q.id),failures:1}).select().single();if(res.error)return toast('No se pudo guardar: '+res.error.message);state.errorLog=e?state.errorLog.map(x=>x.id===e.id?res.data:x):[res.data,...state.errorLog];toast('Repaso programado');renderErrorLog()}
  async function markQuestionDoubt(k){const q=findQuestion(k),e=q&&logFor(q);if(!q)return;const res=e?await state.sb.from('user_error_log').update({uncertain:true,reason:e.reason==='pending'?'doubt':e.reason,next_review_at:new Date(Date.now()+86400000).toISOString()}).eq('id',e.id).eq('user_id',state.user.id).select().single():await state.sb.from('user_error_log').insert({user_id:state.user.id,source_type:q._source||'questions',source_id:String(q.id),uncertain:true,reason:'doubt',next_review_at:new Date(Date.now()+86400000).toISOString()}).select().single();if(res.error)return toast('No se pudo marcar la duda: '+res.error.message);state.errorLog=e?state.errorLog.map(x=>x.id===e.id?res.data:x):[res.data,...state.errorLog];toast('Pregunta dudosa añadida a tus repasos')}
  function reviewErrorQuestion(k){const q=findQuestion(k);if(!q)return;state.bank={pool:[q],index:0,answered:false,selected:null,mode:'immediate',results:[],context:'errors',highlights:{},answers:{},eliminations:{},submitted:false};showQuestion()}
  const oldFeedback=bankFeedbackHtml;
  bankFeedbackHtml=function(q,saved){return oldFeedback(q,saved)+`<div class="dialog-actions"><button class="btn mini" onclick="markQuestionDoubt('${key(q)}')">Marcar como dudosa</button></div>`};

  function topicPriorities(){const map=new Map(),now=Date.now();for(const q of questionPool()){const sp=canonicalSpecialty(q.specialty),topic=q.topic||'General',k=sp+'|'+topic;let v=map.get(k);if(!v){v={sp,topic,questions:[],attempts:[],errors:[],cards:[],score:0};map.set(k,v)}v.questions.push(q)}for(const a of state.attempts.filter(a=>a.is_valid!==false)){const q=getAttemptQuestion(a);if(!q)continue;const v=map.get(canonicalSpecialty(q.specialty)+'|'+(q.topic||'General'));if(v)v.attempts.push(a)}for(const e of state.errorLog){const q=findQuestion(`${e.source_type}:${e.source_id}`);if(!q)continue;const v=map.get(canonicalSpecialty(q.specialty)+'|'+(q.topic||'General'));if(v)v.errors.push(e)}for(const c of dueCards()){const v=map.get(canonicalSpecialty(c.specialty)+'|'+(c.topic||'General'));if(v)v.cards.push(c)}const rows=[...map.values()],maxExam=Math.max(1,...rows.map(v=>v.questions.filter(q=>q.source_exam||q.year).length));for(const v of rows){const recent=v.attempts.filter(a=>now-new Date(a.answered_at).getTime()<90*86400000),ok=recent.filter(a=>a.is_correct).length,mastery=(ok+2)/(recent.length+4),last=Math.max(0,...v.attempts.map(a=>new Date(a.answered_at).getTime())),exam=v.questions.filter(q=>q.source_exam||q.year).length,vulnerable=Math.min(1,v.errors.reduce((n,e)=>n+Math.max(1,e.failures||0),0)/6);v.score=.42*(1-mastery)+.25*(exam?exam/maxExam:.35)+.13*Math.min(1,v.cards.length/8)+.12*vulnerable+.08*Math.min(1,(last?(now-last)/86400000:21)/21);v.level=mastery<.45?'Fundamentos':mastery<.7?'Aplicación':'Casos exigentes';v.last=last;v.mastery=mastery}return rows.sort((a,b)=>b.score-a.score)}
  function renderQuickStudy(){const el=$('#quickStudyPanel');if(!el)return;const rows=topicPriorities();el.innerHTML=`<div class="card"><div class="section-head"><div><h3>No sé qué estudiar</h3><p class="muted">Sesión breve según tus fallos, repasos vencidos y temas con preguntas MIR.</p></div></div><div class="row"><label>Tiempo disponible <select id="quickMinutes"><option value="10">10 minutos</option><option value="20" selected>20 minutos</option><option value="30">30 minutos</option></select></label><button class="btn primary" ${rows.length?'':'disabled'} onclick="startQuickStudy()">Recomendar sesión</button></div><div id="quickRecommendation" class="path"></div></div>`}
  const oldDashboard=renderDashboard;renderDashboard=function(){oldDashboard();$('#view-dashboard').insertAdjacentHTML('afterbegin','<div id="quickStudyPanel"></div>');renderQuickStudy()};
  function startQuickStudy(){const minutes=+$('#quickMinutes').value,rows=topicPriorities(),focus=rows[0];if(!focus)return toast('Publica preguntas para crear una sesión');const budget=Math.max(1,Math.floor((minutes-4)/2));const challenge=q=>{const history=focus.attempts.filter(a=>(a.question_id||a.source_content_id)?.toString()===String(q.id)),fails=history.filter(a=>!a.is_correct).length;return Math.min(1,(fails+1)/(history.length+2))};const target=focus.level==='Fundamentos'?.35:focus.level==='Aplicación'?.55:.8;const sorted=focus.questions.filter(q=>(q.options||[]).length>=2).slice().sort((a,b)=>{const ea=logFor(a),eb=logFor(b),dueA=ea&&new Date(ea.next_review_at)<=new Date()?1:0,dueB=eb&&new Date(eb.next_review_at)<=new Date()?1:0;return (dueB-dueA)||((eb?.failures||0)-(ea?.failures||0))||(Math.abs(challenge(a)-target)-Math.abs(challenge(b)-target))});const pool=sorted.slice(0,Math.min(budget,sorted.length));if(!pool.length)return toast('No hay preguntas válidas para este tema');$('#quickRecommendation').innerHTML=`<strong>${esc(focus.sp)} › ${esc(focus.topic)}</strong> · ${esc(focus.level)} · ${pool.length} preguntas en ${minutes} min · ${focus.cards.length} tarjetas pendientes. Prioridad estimada ${Math.round(focus.score*100)}%.`;state.bank={pool,index:0,answered:false,selected:null,mode:'immediate',results:[],context:'quick',highlights:{},answers:{},eliminations:{},submitted:false};showQuestion()}

  window.openQuestionReport=openQuestionReport;window.saveErrorEntry=saveErrorEntry;window.markQuestionDoubt=markQuestionDoubt;window.reviewErrorQuestion=reviewErrorQuestion;window.startQuickStudy=startQuickStudy;
  window.__nexmirAdaptiveTest={topicPriorities,errorRows};
})();

;
/* NEXMIR V5.0.15 · correcciones de sesión y registro de errores */
(() => {
  const qKey=q=>`${q._source||'questions'}:${q.id}`;
  const questionByKey=k=>questionPool().find(q=>qKey(q)===k);
  const errorFor=q=>state.errorLog.find(e=>e.source_type===(q._source||'questions')&&e.source_id===String(q.id));
  const priorRenderErrors=renderErrors;
  renderErrors=function(){
    priorRenderErrors();
    document.querySelectorAll('.error-controls label').forEach(label=>{if(label.textContent.includes('Fecha de repaso'))label.remove()});
    document.querySelectorAll('.error-controls').forEach(box=>box.classList.remove('cols-3'));
    const text=document.querySelector('#view-errors .section-head p');if(text)text.textContent='Clasifica por qué fallaste, añade una nota y vuelve a resolver. NEXMIR programa el repaso automáticamente.';
  };
  window.saveErrorEntry=async function(k){
    const q=questionByKey(k),e=q&&errorFor(q),reason=document.getElementById(`reason_${k}`)?.value,note=document.getElementById(`note_${k}`)?.value.trim()||'';
    if(!q)return toast('Pregunta no disponible');
    const payload={reason,note,updated_at:new Date().toISOString()};
    const res=e?await state.sb.from('user_error_log').update(payload).eq('id',e.id).eq('user_id',state.user.id).select().single():await state.sb.from('user_error_log').insert({...payload,user_id:state.user.id,source_type:q._source,source_id:String(q.id),failures:1}).select().single();
    if(res.error)return toast('No se pudo guardar: '+res.error.message);
    state.errorLog=e?state.errorLog.map(x=>x.id===e.id?res.data:x):[res.data,...state.errorLog];toast('Guardado');renderErrors();
  };
  window.startQuickStudy=function(){
    const minutes=+document.getElementById('quickMinutes').value,focus=window.__nexmirAdaptiveTest.topicPriorities()[0];
    if(!focus)return toast('Publica preguntas para crear una sesión');
    const pool=focus.questions.filter(q=>canonicalSpecialty(q.specialty)===focus.sp&&(q.topic||'General')===focus.topic&&(q.options||[]).length>=2).sort(()=>Math.random()-.5).slice(0,Math.max(1,Math.floor((minutes-4)/2)));
    if(!pool.length)return toast('No hay preguntas válidas para el tema recomendado');
    state.bank={pool,index:0,answered:false,selected:null,mode:'immediate',results:[],context:'quick',sessionLabel:`Sesión recomendada · ${focus.sp} › ${focus.topic}`,highlights:{},answers:{},eliminations:{},submitted:false};
    showQuestion();
    const head=document.querySelector('#questionDialogBody .dialog-head');if(head&&!document.getElementById('quickSessionLabel'))head.insertAdjacentHTML('afterend',`<div id="quickSessionLabel" class="quick-session-label">${state.bank.sessionLabel}</div>`);
  };
})();
