/* NEXMIR — compañero de estudio. No consultas de red ni temporizadores permanentes. */
(() => {
  'use strict';
  const appearances={clasico:'Clásico',clinico:'Clínico',digital:'Digital',junior:'Junior'};
  const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const storageKey=()=>`nexmir_mascot:${state.user?.id||'guest'}`;
  const read=()=>{try{const p=JSON.parse(localStorage.getItem(storageKey())||'{}');return p&&typeof p==='object'&&!Array.isArray(p)?p:{}}catch{return {}}};
  function prefs(){const p=read();return {style:Object.hasOwn(appearances,p.style)?p.style:'clasico',enabled:p.enabled!==false,motion:p.motion!==false,earned:p.earned&&typeof p.earned==='object'&&!Array.isArray(p.earned)?p.earned:{}}}
  function store(p){try{localStorage.setItem(storageKey(),JSON.stringify(p))}catch{}}
  let infoCache=null;
  function info(){const a=state.attempts,r=state.reviews,s=state.simulations,day=new Date().toDateString();if(!infoCache||infoCache.a!==a||infoCache.n!==a.length||infoCache.r!==r||infoCache.s!==s||infoCache.sn!==s.length||infoCache.day!==day)infoCache={a,n:a.length,r,s,sn:s.length,day,value:window.nexmirResidentInfo?.()||{rank:'R0',level:1,streak:0}};return infoCache.value}
  const specialty=sp=>sp||state.profile?.goal_specialty||'MIR';
  const insignia=sp=>{const n=String(sp).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return /cardio/.test(n)?'♥':/pedi|neonato/.test(n)?'★':/cirug|^cx/.test(n)?'✚':/neuro/.test(n)?'◎':/estad/.test(n)?'Σ':n.split(/[^a-z]+/).filter(Boolean).slice(0,2).map(w=>w[0]).join('').toUpperCase()||'✦'};
  function portrait(sp,mood='calm'){const p=prefs();return `<div class="mascot-portrait mascot-${mood} ${p.motion?'':'mascot-still'}" data-rank="${safe(info().rank)}"><img src="assets/lince-${p.style}.webp" width="480" height="480" loading="lazy" decoding="async" alt="Lince NEXMIR ${safe(appearances[p.style])}, ${safe(info().rank)}"><span class="mascot-pin" aria-label="Distintivo de ${safe(specialty(sp))}">${insignia(specialty(sp))}</span></div>`}
  function panel(message,sp,mood='calm',title='Tu compañero MIR'){if(!prefs().enabled)return '';return `<section class="mascot-panel" data-mascot>${portrait(sp,mood)}<div class="mascot-copy"><span class="mascot-eyebrow">${safe(title)} · ${safe(info().rank)}</span><p>${safe(message)}</p><span class="mascot-specialty">${safe(specialty(sp).toUpperCase())}</span></div></section>`}
  function welcome(){const due=typeof dueCards==='function'?dueCards().length:0;const recent=state.attempts.slice(0,20);if(due)return {mood:'thinking',text:`Hay ${due} flashcards pendientes. Empieza con un bloque pequeño y repasa a tu ritmo.`};if(recent.length>=5){const pct=Math.round(recent.filter(a=>a.is_correct===true).length/recent.length*100);return pct>=80?{mood:'happy',text:`${pct}% de aciertos en tus últimas ${recent.length} preguntas. Buen momento para practicar un tema más exigente.`}:{mood:'support',text:`Tus últimas ${recent.length} preguntas te dan una pista: revisa los errores y vuelve a intentarlo en un bloque breve.`}}return {mood:'calm',text:'Una sesión breve también cuenta. Elige un tema y avancemos paso a paso.'}}
  function mountDashboard(){const root=document.querySelector('#view-dashboard');root?.querySelector('[data-mascot]')?.remove();if(!state.user||!prefs().enabled)return;const m=welcome();root?.querySelector('.home-hero')?.insertAdjacentHTML('afterend',celebrateHtml()||panel(m.text,null,m.mood))}
  function mountProfile(){const root=document.querySelector('#view-profile');if(!root)return;root.querySelector('#mascotSettings')?.remove();const avatar=root.querySelector('.resident-big');if(avatar){avatar.innerHTML=prefs().enabled?portrait(null):safe(info().rank);avatar.classList.toggle('mascot-resident',prefs().enabled)}const p=prefs();root.insertAdjacentHTML('beforeend',`<section class="card" id="mascotSettings"><h3>Tu lince NEXMIR</h3><p class="muted">Elige su apariencia. Las reacciones acompañan tus resultados y respetan el tema del perfil.</p><div class="mascot-choices">${Object.entries(appearances).map(([key,label])=>`<label class="mascot-choice ${p.style===key?'selected':''}"><input type="radio" name="mascotStyle" value="${key}" ${p.style===key?'checked':''} onchange="nexmirMascot.change('style',this.value)"><img src="assets/lince-${key}.webp" width="480" height="480" loading="lazy" decoding="async" alt=""><strong>${label}</strong></label>`).join('')}</div><div class="mascot-toggles"><label><input type="checkbox" ${p.enabled?'checked':''} onchange="nexmirMascot.change('enabled',this.checked)"> Mostrar mascota</label><label><input type="checkbox" ${p.motion?'checked':''} onchange="nexmirMascot.change('motion',this.checked)"> Animaciones suaves</label></div><p class="muted small">Preferencias guardadas para tu cuenta en este navegador. Se respeta la reducción de movimiento del dispositivo.</p></section>`)}
  function change(key,value){if(!['style','enabled','motion'].includes(key)||key==='style'&&!appearances[value])return;store({...prefs(),[key]:value});document.querySelectorAll('[data-mascot]').forEach(n=>n.remove());mountProfile();mountDashboard()}
  function weekly(){const now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),now.getDate()-(now.getDay()+6)%7),ts=+start;return {key:`${start.getFullYear()}-${start.getMonth()+1}-${start.getDate()}`,questions:state.attempts.reduce((n,a)=>n+(Date.parse(a.answered_at)>=ts),0),reviews:state.reviews.reduce((n,r)=>n+(Date.parse(r.last_reviewed_at)>=ts),0),rank:info().rank,streak:info().streak}}
  let celebration=null;
  function checkMilestones(before){if(!state.user)return;const after=weekly(),p=prefs(),plan=state.studyPlan||{},goals=[['questions',Number(plan.weekly_question_goal??350),'¡Meta semanal de preguntas alcanzada!'],['reviews',Number(plan.weekly_review_goal??500),'¡Meta semanal de flashcards alcanzada!']];const hits=[];for(const [kind,goal,text] of goals){const key=`${after.key}:${kind}:${goal}`;if(goal>0&&before[kind]<goal&&after[kind]>=goal&&!p.earned[key]){p.earned[key]=true;hits.push(text)}}if(before.rank!==after.rank){const key=`rank:${after.rank}`;if(!p.earned[key]){p.earned[key]=true;hits.push(`¡Tu residente virtual ha ascendido a ${after.rank}!`)}}for(const days of [3,7,14,30]){const key=`${after.key}:streak:${days}`;if(before.streak<days&&after.streak>=days&&!p.earned[key]){p.earned[key]=true;hits.push(`¡${days} días de constancia! Sigue dejando espacio para descansar.`)}}if(hits.length){p.earned=Object.fromEntries(Object.entries(p.earned).slice(-100));store(p);celebration={user:state.user.id,text:hits.join(' '),at:Date.now()}}}
  function celebrateHtml(sp){if(!prefs().enabled||!celebration||celebration.user!==state.user?.id||Date.now()-celebration.at>60000)return '';return `<div class="mascot-celebration ${prefs().motion?'':'mascot-still'}" data-mascot>${panel(celebration.text,sp,'happy','Meta cumplida')}<div class="mascot-confetti" aria-hidden="true">${Array.from({length:8},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div></div>`}
  function feedback(q,saved){if(!saved?.answered||!prefs().enabled)return '';return celebrateHtml(q.specialty)||panel(saved.correct?'¡Bien resuelto! Antes de seguir, identifica la pista que te llevó a la respuesta.':`Esta pregunta de ${q.topic||specialty(q.specialty)} merece un repaso. Revisa la explicación y qué dato cambia tu elección.`,q.specialty,saved.correct?'happy':'support',saved.correct?'Buen razonamiento':'Seguimos aprendiendo')}
  function resultPanel(total,ok,sp){const pct=total?Math.round(ok/total*100):0;return celebrateHtml(sp)||panel(total?`${ok} de ${total} correctas (${pct}%). ${pct>=80?'Buen bloque: consolida lo aprendido y prueba un nuevo reto.':'El siguiente paso es revisar los errores y las preguntas en blanco, un tema cada vez.'}`:'Elige un bloque breve cuando quieras volver a practicar.',sp,pct>=80?'happy':'support','Sesión completada')}
  function boot(){const oldProfile=window.renderProfile;window.renderProfile=function(...args){const result=oldProfile.apply(this,args);mountProfile();return result};const oldFeedback=window.bankFeedbackHtml;window.bankFeedbackHtml=function(q,saved){return oldFeedback(q,saved)+feedback(q,saved)};
    for(const name of ['persistQuestionAttempt','rateCard','finishMirSimulation']){const original=window[name];window[name]=async function(...args){const before=weekly();const result=await original.apply(this,args);checkMilestones(before);if(name!=='persistQuestionAttempt'&&celebration){const root=name==='rateCard'?document.querySelector('#cardDialog[open] #cardDialogBody'):document.querySelector('#simDialogBody .sim-results-top');const html=celebrateHtml();if(root&&html){root.querySelector('[data-mascot]')?.remove();root.insertAdjacentHTML('beforeend',html)}}return result}}
    const bankResults=window.renderBankResults;window.renderBankResults=function(...args){const result=bankResults.apply(this,args);const b=state.bank;document.querySelector('#questionDialogBody .sim-results-top')?.insertAdjacentHTML('beforeend',resultPanel(b.pool.length,b.results.filter(x=>x.correct===true).length,b.pool[0]?.specialty));return result};
    const simResults=window.renderSimulationResults;window.renderSimulationResults=function(s,main,...args){const result=simResults.call(this,s,main,...args);document.querySelector('#simDialogBody .sim-results-top')?.insertAdjacentHTML('beforeend',resultPanel(s.primaryCount,main.correct,null));return result};
    const oldReview=window.showReviewCard;window.showReviewCard=function(...args){const result=oldReview.apply(this,args);const root=document.querySelector('#cardDialogBody');root?.querySelector('[data-mascot]')?.remove();if(celebration)root?.insertAdjacentHTML('beforeend',celebrateHtml(state.review.pool[state.review.index]?.specialty));return result};
    const oldReviews=window.renderReviews;window.renderReviews=function(...args){const result=oldReviews.apply(this,args);document.querySelector('#view-reviews')?.insertAdjacentHTML('afterbegin',celebrateHtml());return result};
    mountDashboard();if(state.view==='profile')mountProfile();
  }
  window.nexmirMascot={mountDashboard,change,prefs};
  document.addEventListener('visibilitychange',()=>document.documentElement.classList.toggle('mascot-paused',document.hidden));
  window.addEventListener('storage',e=>{if(e.key===storageKey()){mountDashboard();if(state.view==='profile')mountProfile()}});
  setTimeout(boot,0);
})();
