/* NEXMIR V5.1.0 — temas personales, cronómetro, estadísticas y compatibilidad Focus */
(() => {
  const palettes={blue:{name:'Azul',label:'Profesional y clínico'},green:{name:'Verde',label:'Fresco y médico'},orange:{name:'Anaranjado',label:'Energético y cálido'},pink:{name:'Rosado',label:'Cercano y elegante'}};
  const themeStorage='nexmir_theme_v517';
  const timer={running:false,manual:false,kind:null,startedAt:0,elapsed:0,metrics:[],pendingQuestions:0,pendingCards:0};
  const now=()=>Date.now(),isoDate=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)},pad=n=>String(n).padStart(2,'0');
  const fmt=secs=>`${pad(Math.floor(secs/3600))}:${pad(Math.floor(secs%3600/60))}:${pad(secs%60)}`,isoDateFor=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);
  const safe=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));

  function preferredTheme(){let local={};try{local=JSON.parse(localStorage.getItem(themeStorage)||'{}')}catch{};const p=state.profile||{};return{palette:p.theme_palette||local.palette||'blue',mode:p.theme_mode||local.mode||'system'}}
  function resolvedMode(mode){return mode==='system'?(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'):mode}
  function applyTheme(palette,mode){document.documentElement.dataset.palette=palettes[palette]?palette:'blue';document.documentElement.dataset.themeMode=resolvedMode(mode||'system');document.documentElement.dataset.themePreference=mode||'system';document.querySelector('meta[name="theme-color"]')?.setAttribute('content',resolvedMode(mode||'system')==='light'?'#edf4ff':'#081525')}
  function applySavedTheme(){const t=preferredTheme();applyTheme(t.palette,t.mode)}
  matchMedia('(prefers-color-scheme: light)').addEventListener?.('change',()=>{if(document.documentElement.dataset.themePreference==='system')applySavedTheme()});
  function themeChoices(selected){return `<div class="theme-picker"><div class="theme-choice-grid">${Object.entries(palettes).map(([key,p])=>`<label class="theme-choice ${selected.palette===key?'selected':''}"><input type="radio" name="themePalette" value="${key}" onchange="previewThemeChoice(this)" ${selected.palette===key?'checked':''}><span class="theme-preview preview-${key}" aria-hidden="true"><i class="preview-brand">N</i><i class="preview-side"></i><i class="preview-side short"></i><span class="preview-content"><b></b><em></em><em></em><span><i></i><i></i><i></i></span></span></span><strong>${p.name}</strong><small>${p.label}</small></label>`).join('')}</div><div class="theme-mode-row"><strong>Modo</strong><label><input type="radio" name="themeMode" value="system" onchange="previewThemeChoice(this)" ${selected.mode==='system'?'checked':''}> Automático</label><label><input type="radio" name="themeMode" value="light" onchange="previewThemeChoice(this)" ${selected.mode==='light'?'checked':''}> Claro</label><label><input type="radio" name="themeMode" value="dark" onchange="previewThemeChoice(this)" ${selected.mode==='dark'?'checked':''}> Oscuro</label></div></div>`}
  function previewThemeChoice(input){const picker=input.closest('.theme-picker');const palette=picker?.querySelector('input[name="themePalette"]:checked')?.value||'blue';const mode=picker?.querySelector('input[name="themeMode"]:checked')?.value||'system';applyTheme(palette,mode);picker?.querySelectorAll('.theme-choice').forEach(x=>x.classList.toggle('selected',x.querySelector('input')?.checked));}
  async function saveThemeFromInputs(first=false){const palette=document.querySelector('input[name="themePalette"]:checked')?.value||'blue',mode=document.querySelector('input[name="themeMode"]:checked')?.value||'system',row={theme_palette:palette,theme_mode:mode,updated_at:new Date().toISOString()};applyTheme(palette,mode);localStorage.setItem(themeStorage,JSON.stringify({palette,mode}));if(first)$('#themeWelcomeDialog').close();Object.assign(state.profile,row);try{const {error}=await state.sb.from('profiles').update(row).eq('id',state.user.id);if(error)throw error;toast(first?'Tema elegido. Puedes cambiarlo luego en Perfil.':'Tema actualizado')}catch(e){console.warn('Tema pendiente de sincronización',e);toast(first?'Tema aplicado. Se sincronizará cuando Supabase esté disponible.':'Tema aplicado en este dispositivo; falta sincronizarlo.')}if(state.view==='profile')renderProfile();return true}
  function openWelcomeTheme(){if(!state.user)return false;const d=$('#themeWelcomeDialog');if(!d||d.open)return false;$('#themeWelcomeBody').innerHTML=`<div class="dialog-head"><div><span class="chip">Personaliza NEXMIR</span><h2>Elige tu tema visual</h2></div></div><p class="muted">Elige un color y un modo de pantalla. Puedes cambiarlos después desde Perfil.</p>${themeChoices(preferredTheme())}<div class="dialog-actions"><button class="btn" type="button" onclick="document.getElementById('themeWelcomeDialog').close()">Mantener tema actual</button><button class="btn primary" type="button" onclick="saveThemeFromInputs(true)">Guardar y continuar</button></div>`;d.showModal();return true}
  window.saveThemeFromInputs=saveThemeFromInputs;window.previewThemeChoice=previewThemeChoice;window.nexmirOpenWelcomeTheme=openWelcomeTheme;

  function totalElapsed(){return timer.elapsed+(timer.running?Math.floor((now()-timer.startedAt)/1000):0)}
  function updateClock(){const value=fmt(totalElapsed()),top=$('#studyTimerBtn'),big=$('#studyTimerBig'),control=$('#studyTimerManualBtn');if(top)top.textContent=`⏱ ${value}`;if(big)big.textContent=value;if(control)control.textContent=timer.running?'Pausar':'Reanudar'}
  async function loadStudyMetrics(){if(!state.user)return;const {data,error}=await state.sb.from('user_study_daily').select('*').eq('user_id',state.user.id).order('activity_date',{ascending:false});if(!error){timer.metrics=data||[];state.studyMetrics=timer.metrics}}
  async function flushStudyTime(force=false){if(!state.user)return;const seconds=timer.running?Math.floor((now()-timer.startedAt)/1000):0;if(!force&&seconds<20&&!timer.pendingQuestions&&!timer.pendingCards)return;if(timer.running){timer.elapsed+=seconds;timer.startedAt=now()}const date=isoDate();let row=timer.metrics.find(x=>x.activity_date===date);if(!row)row={user_id:state.user.id,activity_date:date,study_seconds:0,questions_answered:0,flashcards_reviewed:0,simulations_completed:0};const next={user_id:state.user.id,activity_date:date,study_seconds:(row.study_seconds||0)+(timer.running?seconds:0),flashcards_reviewed:(row.flashcards_reviewed||0)+timer.pendingCards,simulations_completed:Number(row.simulations_completed||0),updated_at:new Date().toISOString()};if(window.NEXMIR_FOCUS_BACKEND_READY!==true)next.questions_answered=(row.questions_answered||0)+timer.pendingQuestions;timer.pendingQuestions=0;timer.pendingCards=0;const {data,error}=await state.sb.from('user_study_daily').upsert(next,{onConflict:'user_id,activity_date'}).select().single();if(!error){const i=timer.metrics.findIndex(x=>x.activity_date===date);if(i>=0)timer.metrics[i]=data||next;else timer.metrics.unshift(data||next);state.studyMetrics=timer.metrics}}
  function beginStudy(kind,manual=false){timer.kind=kind||timer.kind||'study';timer.manual=manual||timer.manual;if(timer.running||document.hidden)return;timer.running=true;timer.startedAt=now();updateClock()}
  function pauseStudy(force=true){if(!timer.running)return;flushStudyTime(force);timer.running=false;timer.startedAt=0;updateClock()}
  window.toggleStudyTimerManual=()=>{if(timer.running){timer.manual=true;pauseStudy(true)}else{timer.manual=true;beginStudy('manual',true)}updateClock()};
  function metricSeconds(){return timer.metrics.reduce((s,x)=>s+(x.study_seconds||0),0)+totalElapsed()}
  function streak(){if(state.studyStreak&&Number.isFinite(Number(state.studyStreak.current_streak)))return Number(state.studyStreak.current_streak);const dates=new Set(timer.metrics.filter(x=>(x.study_seconds||0)>=60).map(x=>x.activity_date));let d=new Date(),n=0;while(dates.has(isoDateFor(d))){n++;d=new Date(d.getTime()-864e5)}return n}
  function profileStatsHtml(){const attempts=(state.attempts||[]).filter(a=>a.is_valid!==false),correct=attempts.filter(a=>a.is_correct).length,accuracy=attempts.length?Math.round(correct*100/attempts.length):0,totalCards=state.reviews.filter(x=>x.last_reviewed_at).length,today=timer.metrics.find(x=>x.activity_date===isoDate())||{},sims=(state.simulations||[]).filter(x=>x.finished_at).length,weak=(typeof weakSpecialties==='function'?weakSpecialties()[0]:null);return `<div class="profile-stats"><div class="section-head"><div><h3>Tu estudio en números</h3><p class="muted">Tiempo activo registrado en preguntas, flashcards/repasos y simulacros.</p></div><span class="chip">${streak()} día${streak()===1?'':'s'} de racha</span></div><div class="grid cols-4 stats-grid"><div class="card stat-card"><b>${fmt(metricSeconds())}</b><span>Tiempo total</span></div><div class="card stat-card"><b>${fmt(today.study_seconds||0)}</b><span>Hoy</span></div><div class="card stat-card"><b>${today.flashcards_reviewed||0}</b><span>Flashcards hoy</span></div><div class="card stat-card"><b>${totalCards}</b><span>Flashcards dadas</span></div><div class="card stat-card"><b>${attempts.length}</b><span>Preguntas respondidas</span></div><div class="card stat-card"><b>${accuracy}%</b><span>Precisión global</span></div><div class="card stat-card"><b>${sims}</b><span>Simulacros terminados</span></div><div class="card stat-card"><b>${weak?safe(weak.name):'—'}</b><span>Área a reforzar</span></div></div></div>`}
  function showMotivation(total){const next=total>=70?Math.ceil((total+1)/50)*50:[10,20,50,70].find(n=>n>total)||50,messages={10:'Primer bloque completado. La constancia gana al impulso.',20:'Veinte preguntas: ya estás entrenando criterio MIR.',50:'50 preguntas completadas. Pausa breve, respira y sigue.',70:'70 preguntas: excelente sesión. Cada error bien revisado te acerca.'};toast('✨ '+(messages[total]||`¡${total} preguntas respondidas! Siguiente meta: ${next}.`))}
  function isMilestone(n){return[10,20,50,70].includes(n)||(n>70&&n%50===0)}
  function wrap(name,after){const original=window[name];if(typeof original!=='function')return;window[name]=function(...args){const result=original.apply(this,args);return Promise.resolve(result).then(value=>{after(args,value);return value})}}
  function enhanceProfile(){const base=window.renderProfile;window.renderProfile=function(){base();const root=$('#view-profile');if(!root)return;const cards=root.querySelector('.grid.cols-2');cards?.insertAdjacentHTML('afterend',`<div class="card profile-theme-card"><div class="section-head"><div><span class="chip">Apariencia</span><h3>Tu tema NEXMIR</h3></div></div>${themeChoices(preferredTheme())}<button class="btn primary" onclick="saveThemeFromInputs(false)">Guardar tema</button></div>${profileStatsHtml()}`)}}
  function injectFocus(){$('#studyTimerBtn')?.addEventListener('click',()=>{$('#studyTimerDialog').showModal();updateClock()})}
  function boot(){applySavedTheme();injectFocus();enhanceProfile();loadStudyMetrics().then(()=>{if(state.view==='profile')renderProfile()});const oldShow=window.showApp;window.showApp=function(){applySavedTheme();oldShow()};wrap('startBank',()=>beginStudy('questions'));wrap('startReview',()=>beginStudy('flashcards'));wrap('startSingleCard',()=>beginStudy('flashcards'));wrap('startMirSimulation',()=>beginStudy('simulation'));wrap('resumeMirSimulation',()=>beginStudy('simulation'));wrap('persistQuestionAttempt',()=>{timer.pendingQuestions++;flushStudyTime(true);const total=state.attempts.length;if(isMilestone(total))setTimeout(()=>showMotivation(total),200)});wrap('rateCard',()=>{timer.pendingCards++;flushStudyTime(true)});wrap('finishBank',()=>pauseStudy(true));wrap('finishMirSimulation',()=>pauseStudy(true));$('#questionDialog')?.addEventListener('close',()=>{if(timer.kind==='questions')pauseStudy(true)});$('#cardDialog')?.addEventListener('close',()=>{if(timer.kind==='flashcards')pauseStudy(true)});$('#simDialog')?.addEventListener('close',()=>{if(timer.kind==='simulation')pauseStudy(true)});document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseStudy(true);else if(timer.manual)beginStudy('manual',true)});window.addEventListener('pagehide',()=>pauseStudy(true));setInterval(()=>{if(timer.running)flushStudyTime(false);updateClock()},1000)}
  setTimeout(boot,0);
})();
