const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const base=path.join(__dirname,'..');
class Element{
 constructor(){this.children=[];this.hidden=false;this.value='';this.dataset={};this.style={};this.events={};this.classList={add(){},remove(){},toggle(){}};this.tagName='DIV';this.textContent='';this.disabled=false}
 set innerHTML(v){this.html=v;this.children=[]}get innerHTML(){return this.html||''}
 appendChild(x){this.children.push(x);return x}replaceChildren(...xs){this.children=xs;this.value=xs[0]?.value||''}
 setAttribute(k,v){this[k]=v}focus(){this.doc.activeElement=this}addEventListener(k,f){this.events[k]=f}
 querySelectorAll(){return this.children}querySelector(){return null}remove(){}scrollIntoView(){}
}
function dom(){const nodes=new Map(),events={};const document={events,activeElement:{tagName:'BODY'},documentElement:{dataset:{}},body:{style:{},insertAdjacentHTML(){}},getElementById(id){if(!nodes.has(id)){const e=new Element;e.doc=document;nodes.set(id,e)}return nodes.get(id)},createElement(){const e=new Element;e.doc=document;return e},querySelector(sel){return this.getElementById(sel)},addEventListener(k,f){events[k]=f}};return {document,nodes}}
function game(){const {document}=dom(),messages=[],listeners={},parent={postMessage(x){messages.push(x)}};const context={document,parent,location:{origin:'https://nexmir.test'},console,setTimeout:f=>f(),matchMedia:()=>({matches:true,addEventListener(){}}),localStorage:{getItem(){return null}},Option:function(t,v=t){this.text=t;this.value=v},addEventListener(k,f){listeners[k]=f}};context.window=context;vm.createContext(context);const html=fs.readFileSync(path.join(base,'arcade/codigo-vital.html'),'utf8');vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],context);const run=s=>vm.runInContext(s,context);function init(questions){listeners.message({source:parent,origin:context.location.origin,data:{type:'nexmir:arcade-init',palette:'pink',mode:'dark',specialties:['Neumología','Cardiología'],questions}})}return{document,context,run,init,listeners,messages,parent}}
const q={answer:'PEÑA-ÁRBOL',specialty:'Neumología',category:'Perlas',clue:'Paciente ficticio. ¿Cuál es el término?',explanation:'Texto <img src=x onerror=alert(1)> de prueba.'};
test('Handshake, inherited theme, modal cancel preserves game and blocks guesses',()=>{const g=game();assert.equal(g.messages[0].type,'nexmir:arcade-ready');g.init([q]);assert.equal(g.document.documentElement.dataset.palette,'pink');assert.equal(g.document.getElementById('specialty-modal').hidden,false);g.run("guess('Z')");assert.equal(g.run('errors'),0);g.run("closeSpecialtyModal();guess('Z');openSpecialtyModal();closeSpecialtyModal()");assert.equal(g.run('errors'),1);assert.equal(g.run('specialty'),'Neumología');assert.equal(g.document.querySelector('main').inert,false)});
test('Spaces, accents, Ñ, win and escaped explanation',()=>{const g=game();g.init([q]);g.run('closeSpecialtyModal()');assert.equal(g.run('current.a'),'PEÑA-ARBOL');g.run("for(const ch of new Set(current.a)){if(LETTERS.includes(ch))guess(ch)}");assert.equal(g.run('won'),true);assert.equal(g.run('errors'),0);assert.ok(g.document.getElementById('result').innerHTML.includes('&lt;img'));assert.ok(!g.document.getElementById('result').innerHTML.includes('<img'))});
test('Six misses lose; hints cost one and disable on last attempt',()=>{const g=game();g.init([{...q,answer:'AAA'}]);g.run("closeSpecialtyModal();for(const ch of 'BCDEF')guess(ch)");assert.equal(g.run('errors'),5);assert.equal(g.document.getElementById('hint').disabled,true);g.run("hint();guess('G')");assert.equal(g.run('errors'),6);assert.equal(g.run('finished'),true);assert.equal(g.run('won'),false);const other=game();other.init([{...q,answer:'ABC'}]);other.run('closeSpecialtyModal();hint()');assert.equal(other.run('errors'),1);assert.equal(other.run('used.length'),1)});
test('Specialty and category filters remain within the selected pool',()=>{const g=game();g.init([q,{...q,answer:'OTRO',specialty:'Cardiología',category:'Pruebas'}]);g.run("chooseSpecialty('Cardiología')");assert.equal(g.run('current.a'),'OTRO');assert.equal(g.run('current.s'),'Cardiología');assert.equal(g.document.getElementById('topic').children[1].value,'Pruebas');g.run("chooseSpecialty('Unknown')");assert.equal(g.run('specialty'),'Cardiología')});
test('Cross-origin messages cannot replace game data; escape closes safely',()=>{const g=game();g.init([q]);g.listeners.message({source:g.parent,origin:'https://evil.test',data:{type:'nexmir:arcade-init',questions:[{...q,answer:'EVIL'}]}});assert.equal(g.run('current.a'),'PEÑA-ARBOL');g.document.events.keydown({key:'Escape'});assert.equal(g.document.getElementById('specialty-modal').hidden,true)});
test('Admin validation, role guard and no insertion on unauthorized access',()=>{const {document}=dom();let calls=0;const context={document,go(){},logoutCloud:async()=>{},cloudMode:true,sb:{from(){calls++;throw Error('No writes expected')}},cloudUser:{id:'test'},cloudRole:'moderator',RemnoteTaxonomy:{unclassified:x=>!x},console};context.window=context;vm.createContext(context);let code=fs.readFileSync(path.join(base,'admin/arcade_manager.js'),'utf8');code=code.replace(/\}\)\(\);\s*$/,'globalThis.check={allowed,valid,save};})();');vm.runInContext(code,context);assert.equal(context.check.allowed(),false);context.cloudRole='admin';assert.equal(context.check.allowed(),true);assert.equal(context.check.valid({specialty:'Neumología',answer:'PEÑA',clue:'¿Cuál es el diagnóstico?'}),'');assert.match(context.check.valid({specialty:'N',answer:'A2',clue:'¿Qué?'}),/letras/);context.cloudRole='moderator';context.check.save({preventDefault(){}});assert.equal(calls,0)});
test('SQL policies, repeat-safe seed and integration points',()=>{const sql=fs.readFileSync(path.join(base,'supabase/ARCADE.sql'),'utf8');assert.match(sql,/enable row level security/);assert.match(sql,/revoke all.*from anon/);assert.match(sql,/for all to authenticated.*role='admin'.*with check/s);assert.match(sql,/on conflict\(id\) do nothing/);assert.equal((sql.match(/a7cade00-0000-4000-8000-/g)||[]).length,16);for(const file of ['index.html','admin/index.html'])assert.ok(fs.readFileSync(path.join(base,file),'utf8').includes('data-view="arcade"'));assert.ok(fs.readFileSync(path.join(base,'tutorial.js'),'utf8').includes("['arcade'"))});
