/* NEXMIR V4.8 · Importador universal de bancos */
(() => {
  const st={mode:'single',questions:[],images:new Map(),taxonomy:[],existing:new Map(),selected:new Set(),filter:'all',sourceKind:'bank_pdf_single',analyzing:false};
  const $b=s=>document.querySelector(s), $$b=(s,r=document)=>[...r.querySelectorAll(s)];
  const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9ñ]+/g,' ').replace(/\s+/g,' ').trim();
  const slug=s=>norm(s).replace(/ñ/g,'n').replace(/\s+/g,'-').replace(/^-|-$/g,'')||'banco';
  const reEsc=s=>String(s).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
  const DEFAULT_BRANDS=['Academia MIR','AMIR','Grupo CTO','CTO','PROMIR','MIR Asturias','MIRMeApp','Mirmedic'];
  const RULES=[
    ['Cardiología',/(infarto|iam\b|stent|coronari|angina|electrocard|ecg\b|arritm|fibrilaci[oó]n auricular|flutter|valvul|insuficiencia cardiaca|miocard|pericard)/i],
    ['Gastroenterología',/(es[oó]fag|g[aá]stric|helicobacter|intestin|colon|crohn|colitis|celiaqu|pancrea|h[eé]pat|cirrosis|colang|colecist|digestiv)/i],
    ['Neurología',/(ictus|epilep|convulsi|cefalea|parkinson|alzheimer|esclerosis m[uú]ltiple|neuropat|glioma|cerebral|afasia|ataxia)/i],
    ['Neumología',/(asma\b|epoc|pulmon|neumon|bronqui|pleura|espirom|fev1|tiffeneau|neumot[oó]rax|embolia pulmonar)/i],
    ['Enfermedades Infecciosas',/(vih\b|sida|herpes|tuberculosis|aspergill|bacter|virus|sepsis|antibi[oó]tic|malaria|infecci[oó]n|mic[oó]tic)/i],
    ['Endocrinología y Nutrición',/(diabetes|insulina|tiroid|suprarrenal|adrenal|feocromocitoma|cushing|addison|hip[oó]fisis|paratiroid|metanefrina)/i],
    ['Nefrología',/(renal|riñ[oó]n|glomerul|nefrot|nefr[ií]tic|creatinina|di[aá]lisis|proteinuria|hematuria)/i],
    ['Hematología',/(anemia|leucemia|linfoma|mieloma|plaqueta|coagul|hemofilia|trombocit|pancitopen)/i],
    ['Reumatología',/(lupus|artritis reumatoide|espondil|vasculitis|beh[cç]et|gota\b|escleroderm|sj[oö]gren|reumat)/i],
    ['Pediatría',/(reci[eé]n nacido|neonatal|prematur|lactante|niñ[oa]|pediatr|membrana hialina)/i],
    ['Ginecología y Obstetricia',/(embaraz|gestaci[oó]n|parto|placenta|ovario|uter|cervix|amenorrea|ginecol|cardiotocogr|eclamps)/i],
    ['Psiquiatría',/(depresi[oó]n|esquizof|psicosis|bipolar|ansiedad|suicid|antipsic[oó]tic|adicci[oó]n)/i],
    ['Epidemiología y Medicina Preventiva',/(ensayo cl[ií]nico|sensibilidad|especificidad|odds ratio|riesgo relativo|nnt\b|intervalo de confianza|cribado|meta-?an[aá]lisis|forest plot|epidemiolog|bioestad)/i],
    ['Dermatología',/(piel|cut[aá]ne|dermat|psoriasis|liquen|melanoma|nevus|prurito|ampolla)/i],
    ['Traumatología y Cirugía Ortopédica',/(fractura|luxaci[oó]n|escoliosis|tobillo|rodilla|cadera|osteos[ií]ntesis|menisco|ligamento)/i],
    ['Urología',/(pr[oó]stata|test[ií]culo|vejiga|urolog|litiasis|pene|escroto)/i],
    ['Otorrinolaringología',/(laringe|faringe|hipoacusia|rinne|weber|v[eé]rtigo|otitis|o[ií]do|cuerda vocal)/i],
    ['Oftalmología',/(retina|glaucoma|catarata|ojo\b|ocular|fondo de ojo|agudeza visual|papila [oó]ptica)/i],
    ['Oncología Médica',/(c[aá]ncer|carcinoma|tumor maligno|met[aá]stasis|quimioterapia|radioterapia|oncolog|neoplasia)/i],
    ['Radiología y Urgencias',/(radiograf[ií]a|tomograf[ií]a|\btc\b|resonancia magn[eé]tica|\brm\b|ecograf[ií]a|urgencias|politrauma)/i],
    ['Cirugía General',/(cirug[ií]a|postoperator|laparoscop|apendic|hernia|abdomen agudo|peritonitis)/i],
    ['Farmacología',/(f[aá]rmaco|farmacol|efecto adverso|ant[ií]doto|toxicidad|interacci[oó]n|dosis)/i],
    ['Inmunología y Genética',/(inmunolog|anticuerpo|complemento|hipersensibilidad|mutaci[oó]n|gen\b|citogen|herencia|cariotipo)/i],
    ['Bioética y Medicina Legal',/(consentimiento informado|bio[eé]tica|confidencial|secreto profesional|medicina legal|eutanasia)/i],
    ['Anatomía y Fisiología',/(anatom[ií]a|plexo braquial|conducto tor[aá]cico|fisiolog[ií]a)/i]
  ];
  function brands(){const extra=($b('#bankExtraBrands')?.value||'').split(',').map(x=>x.trim()).filter(Boolean);return[...new Set([...DEFAULT_BRANDS,...extra])].sort((a,b)=>b.length-a.length)}
  function scrub(v=''){let s=String(v||'').replace(/\b(?:https?:\/\/)?(?:www\.)?[a-z0-9][a-z0-9.-]*\.(?:com|es|net|org|edu)(?:\/\S*)?/gi,' ');for(const b of brands())s=s.replace(new RegExp(`\\b${reEsc(b)}\\b`,'gi'),' ');return s.replace(/\s{2,}/g,' ').replace(/\s+([,.;:!?])/g,'$1').trim()}
  function cleanLine(l=''){let s=scrub(String(l||'').replace(/\s+/g,' ').trim());if(!s)return'';if(/^(MEDICINA|CUADERNO DE EXAMEN|CUADERNILLO DE IM[AÁ]GENES|PRUEBAS SELECTIVAS|P[aá]g\.?\s*\d+|SIMULACRO|BANCO DE PREGUNTAS)$/i.test(s))return'';if(/^M\d+[A-Z]{2}$/i.test(s))return'';return s}
  function smart(lines){let out='';for(const raw of lines||[]){const l=cleanLine(raw);if(!l)continue;if(!out)out=l;else if(/-$/.test(out)&&/^[a-záéíóúüñ]/i.test(l))out=out.slice(0,-1)+l;else out+=' '+l}return scrub(out.replace(/\s+/g,' ').trim())}
  function setProg(p,t=''){p=Math.max(0,Math.min(100,Math.round(p)));$b('#bankProgressBar').style.width=p+'%';$b('#bankProgressText').textContent=`${p}%${t?' · '+t:''}`}
  function showProg(on){$b('#bankProgress')?.classList.toggle('hidden',!on)}
  async function loadPdf(file){if(!window.pdfjsLib)throw new Error('No se pudo cargar PDF.js. Comprueba la conexión a internet.');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';return pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise}
  async function pageLines(page){const vp=page.getViewport({scale:1}),tc=await page.getTextContent(),half=vp.width/2,cols=[[],[]];for(const it of tc.items){if(!it.str?.trim())continue;const x=it.transform?.[4]||0,y=it.transform?.[5]||0;cols[x<half?0:1].push({x,y,str:it.str})}const lines=[];for(const arr of cols){arr.sort((a,b)=>Math.abs(b.y-a.y)>2?b.y-a.y:a.x-b.x);let cur=[],ly=null;const flush=()=>{if(cur.length){lines.push(cur.sort((a,b)=>a.x-b.x).map(v=>v.str).join(' '));cur=[]}};for(const it of arr){if(ly===null||Math.abs(it.y-ly)<=2.5){cur.push(it);if(ly===null)ly=it.y}else{flush();cur=[it];ly=it.y}}flush()}return lines.map(cleanLine).filter(Boolean)}
  function qStart(line){const m=String(line||'').match(/^(\d{1,3})\.\s+(.+)$/);if(!m)return null;const n=+m[1],rest=m[2].trim();if(n<1||n>1000)return null;if(/Pregunta\s+(?:asociada|vinculada)\s+a\s+la\s+imagen/i.test(rest))return n;if(n>=5)return n;if(n<=4 && rest.length>=55 && /[¿?:]/.test(rest))return n;return null}
  async function extractLines(file,base=0,span=45){const doc=await loadPdf(file),out=[];let started=false;for(let p=1;p<=doc.numPages;p++){const lines=await pageLines(await doc.getPage(p)),hits=lines.map(qStart).filter(Boolean);if(!started&&(hits.length>=2||hits.includes(1)||lines.some(x=>/Pregunta\s+(?:asociada|vinculada)/i.test(x))))started=true;if(started)out.push(...lines);setProg(base+span*(p/doc.numPages),`Leyendo ${file.name} · pág. ${p}/${doc.numPages}`)}if(!out.length)throw new Error(`No pude localizar preguntas en ${file.name}.`);return out}
  function blocks(lines){const starts=[];lines.forEach((l,i)=>{const n=qStart(l);if(n)starts.push([i,n])});const m=new Map();for(let k=0;k<starts.length;k++){const [i,n]=starts[k],end=k+1<starts.length?starts[k+1][0]:lines.length;(m.get(n)||m.set(n,[]).get(n)).push(lines.slice(i,end))}return m}
  function parseQ(block,n){if(!block?.length)return null;let first=String(block[0]).replace(new RegExp('^'+n+'\\.\\s*'),'').trim(),image=null;const im=first.match(/^Pregunta\s+(?:asociada|vinculada)\s+a\s+la\s+imagen\s+(\d+)\s*:\s*(.*)$/i);if(im){image=+im[1];first=im[2]||''}const src=[];for(const l of[first,...block.slice(1)]){if(/^(?:Respuesta\s+correcta|Respuesta|Soluci[oó]n)\s*:/i.test(l)||/^(?:Comentario|Explicaci[oó]n)\s*:/i.test(l))break;src.push(l)}const opts=['','','',''],stem=[];let cur=-1;for(const raw of src){const l=cleanLine(raw);if(!l)continue;const om=l.match(/^([1-4])\.\s*(.*)$/);if(om){cur=+om[1]-1;opts[cur]=om[2]||''}else if(cur<0)stem.push(l);else opts[cur]=(opts[cur]+' '+l).trim()}return{number:n,image_number:image,stem:smart(stem),options:opts.map(x=>smart([x]))}}
  function parseA(block){if(!block?.length)return{correct_index:null,explanation:''};const lines=block.map(cleanLine).filter(Boolean);let correct=null,at=-1;for(let i=0;i<lines.length;i++){const l=lines[i];if(correct===null){const m=l.match(/(?:Respuesta\s+correcta|Respuesta|Correcta|Soluci[oó]n)\s*:\s*(?:opci[oó]n\s*)?([1-4A-D])/i);if(m)correct=/[A-D]/i.test(m[1])?m[1].toUpperCase().charCodeAt(0)-65:+m[1]-1}if(at<0&&/(?:Comentario|Explicaci[oó]n|Soluci[oó]n\s+comentada)\s*:/i.test(l))at=i}let explanation='';if(at>=0){const first=lines[at].replace(/^.*?(?:Comentario|Explicaci[oó]n|Soluci[oó]n\s+comentada)\s*:\s*/i,'');explanation=smart([first,...lines.slice(at+1).filter(x=>!/(?:Respuesta\s+correcta|Respuesta|Correcta|Soluci[oó]n)\s*:/i.test(x))])}return{correct_index:correct,explanation}}
  function merge(groups,n){const ps=[];for(const bs of groups)for(const b of bs||[]){const p=parseQ(b,n);if(p)ps.push(p)}if(!ps.length)return null;return{number:n,image_number:ps.find(p=>p.image_number)?.image_number||null,stem:ps.map(x=>x.stem).sort((a,b)=>b.length-a.length)[0]||'',options:[0,1,2,3].map(i=>ps.map(p=>p.options[i]||'').filter(Boolean).sort((a,b)=>b.length-a.length)[0]||'')}}
  function bestA(bs){let correct=null,exp='';for(const b of bs||[]){const a=parseA(b);if(correct===null&&a.correct_index!==null)correct=a.correct_index;if(a.explanation.length>exp.length)exp=a.explanation}return{correct_index:correct,explanation:exp}}
  async function extractImages(file,base=58,span=25){if(!file)return new Map();const doc=await loadPdf(file),map=new Map();for(let p=1;p<=doc.numPages;p++){const page=await doc.getPage(p),scale=1.55,vp=page.getViewport({scale}),tc=await page.getTextContent(),items=tc.items.filter(x=>x.str?.trim()).map(x=>({str:scrub(x.str.trim()),x:x.transform?.[4]||0,y:x.transform?.[5]||0}));items.sort((a,b)=>Math.abs(b.y-a.y)>2?b.y-a.y:a.x-b.x);let line=[],ly=null,labels=[];const flush=()=>{if(!line.length)return;const txt=line.sort((a,b)=>a.x-b.x).map(x=>x.str).join(' ').trim(),m=txt.match(/^IMAGEN\s+(\d+)$/i);if(m){const pt=vp.convertToViewportPoint(line[0].x,line[0].y);labels.push({n:+m[1],y:pt[1]})}line=[]};for(const it of items){if(ly===null||Math.abs(it.y-ly)<=2.5){line.push(it);if(ly===null)ly=it.y}else{flush();line=[it];ly=it.y}}flush();if(labels.length){labels.sort((a,b)=>a.y-b.y);const c=document.createElement('canvas');c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);await page.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;for(let i=0;i<labels.length;i++){const l=labels[i],next=labels[i+1],x=Math.round(18*scale),y=Math.max(0,Math.round(l.y+14*scale)),ey=next?Math.round(next.y-10*scale):Math.round(vp.height-28*scale),w=Math.max(20,c.width-x*2),h=Math.max(20,ey-y),crop=document.createElement('canvas');crop.width=w;crop.height=h;crop.getContext('2d').drawImage(c,x,y,w,h,0,0,w,h);const blob=await new Promise(r=>crop.toBlob(r,'image/jpeg',.88));if(blob)map.set(l.n,{blob,url:URL.createObjectURL(blob)})}}setProg(base+span*(p/doc.numPages),`Extrayendo imágenes · pág. ${p}/${doc.numPages}`)}return map}
  function inferSpecialty(q){const txt=norm([q.stem,...q.options,q.explanation].join(' '));for(const [sp,re] of RULES)if(re.test(txt))return sp;return'Sin clasificar'}
  function score(label,text){const n=norm(label);if(!n||n==='general')return 0;let s=text.includes(n)?10:0;for(const t of n.split(' ').filter(x=>x.length>=5))if(text.includes(t))s++;return s}
  function inferTopic(q,sp){const text=norm([q.stem,...q.options,q.explanation].join(' ')),rows=st.taxonomy.filter(x=>x.specialty===sp);let best=null,bs=0;for(const r of rows){const s=score(r.topic,text)*2+score(r.subtopic,text)+score(r.section,text);if(s>bs){bs=s;best=r}}return bs>=2?{topic:best.topic||'General',subtopic:best.subtopic||null,section:best.section||null}:{topic:'General',subtopic:null,section:null}}
  async function loadTaxonomy(){st.taxonomy=[];if(!cloudMode||!sb)return;const{data}=await sb.from('content_items').select('specialty,topic,subtopic,section').eq('status','published');const seen=new Set();for(const r of data||[]){const k=[r.specialty,r.topic,r.subtopic,r.section].join('|');if(!seen.has(k)){seen.add(k);st.taxonomy.push(r)}}}
  async function loadRemnote(file){if(!file)throw new Error('Selecciona la exportación de RemNote.');const out=[];if(file.name.toLowerCase().endsWith('.zip')){const z=await JSZip.loadAsync(file),es=Object.values(z.files).filter(x=>!x.dir&&/\.(md|markdown)$/i.test(x.name));for(let i=0;i<es.length;i++){out.push({name:es[i].name,text:await es[i].async('string')});setProg(10+35*((i+1)/es.length),`Leyendo RemNote ${i+1}/${es.length}`)}}else out.push({name:file.name,text:await file.text()});return out}
  async function existing(name){st.existing=new Map();if(!cloudMode||!sb)return;try{const data=await fetchAllPages(()=>sb.from('questions').select('*').like('source_uid',`bank:${slug(name)}:%`));for(const r of data||[])if(r.source_uid)st.existing.set(r.source_uid,r)}catch(e){console.warn('No se pudo consultar duplicados del banco',e)}}
  function signature(q){return JSON.stringify([q.stem,q.options,q.correct_index,q.explanation,q.specialty,q.topic,q.subtopic,q.section])}
  function classifyStatuses(name){st.selected.clear();for(const q of st.questions){q.source_uid=q.native_uid?`bank:${slug(name)}:${q.native_uid}`:`bank:${slug(name)}:q${q.number}`;const old=st.existing.get(q.source_uid);if(old&&q.native_uid&&q.classification_origin!=='remnote_hierarchy'&&!isUnclassifiedValue(old.specialty))for(const k of ['specialty','topic','subtopic','section'])q[k]=old[k];q.status_import=!old?'new':signature(q)===signature({...old,options:Array.isArray(old.options)?old.options:[]})?'unchanged':'modified';q.db_id=old?.id||null;if(q.status_import!=='unchanged')st.selected.add(q.source_uid)}}
  function problems(q){const r=[],valid=q.options.filter(x=>String(x||'').trim()).length;if(valid<4)r.push(`Solo ${valid}/4 alternativas`);if(q.correct_index===null||q.correct_index===undefined)r.push('Sin respuesta correcta');if(!String(q.explanation||'').trim())r.push('Sin explicación');return r}
  function filtered(){let a=st.questions,f=st.filter,t=norm($b('#bankSearch')?.value||'');if(f==='review')a=a.filter(x=>x.specialty==='Sin clasificar');else if(f==='problems')a=a.filter(x=>problems(x).length);else if(f!=='all')a=a.filter(x=>x.status_import===f);if(t)a=a.filter(x=>norm(`${x.number} ${x.stem} ${x.specialty} ${x.topic}`).includes(t));return a}
  function render(){const qs=st.questions;const p=qs.filter(x=>problems(x).length),un=qs.filter(x=>x.specialty==='Sin clasificar').length;$b('#bankStats').innerHTML=`<div class="stat"><div class="num">${qs.length}</div><div class="label">Preguntas</div></div><div class="stat"><div class="num">${qs.filter(x=>x.correct_index!==null).length}</div><div class="label">Respuestas</div></div><div class="stat"><div class="num">${qs.filter(x=>x.explanation).length}</div><div class="label">Explicaciones</div></div><div class="stat"><div class="num">${st.images.size}</div><div class="label">Imágenes</div></div><div class="stat"><div class="num">${un}</div><div class="label">Sin clasificar</div></div><div class="stat"><div class="num">${p.length}</div><div class="label">Problemas</div></div>`;const qual=$b('#bankQuality');qual.classList.toggle('hidden',!p.length);qual.innerHTML=p.length?`<strong>⚠ ${p.length} preguntas requieren revisión.</strong> Usa la pestaña “Con problemas” y abre la pregunta para corregirla.`:'';renderList()}
  function renderList(){const a=filtered();$b('#bankSelectedCount').textContent=`${st.selected.size} seleccionadas`;$b('#bankQuestionList').innerHTML=a.length?a.map(q=>`<div class="simqRow" data-n="${q.number}"><input class="bankSel" type="checkbox" ${st.selected.has(q.source_uid)?'checked':''} ${q.status_import==='unchanged'?'disabled':''}><div><span class="badge ${q.status_import}">${q.status_import==='new'?'Nueva':q.status_import==='modified'?'Modificada':'Sin cambios'}</span>${problems(q).length?'<span class="badge">⚠ '+problems(q).length+'</span>':''}</div><div><div class="question">${q.number}. ${esc(q.stem||'')}</div><div class="meta">Correcta: ${q.correct_index==null?'—':String.fromCharCode(65+q.correct_index)} · ${esc(q.specialty)} › ${esc(q.topic||'General')}</div></div><div class="chev">›</div></div>`).join(''):'<div class="empty">No hay preguntas con este filtro.</div>';$$b('#bankQuestionList .simqRow').forEach(row=>{const q=st.questions.find(x=>x.number===+row.dataset.n);row.querySelector('.bankSel').onclick=ev=>{ev.stopPropagation();ev.target.checked?st.selected.add(q.source_uid):st.selected.delete(q.source_uid);renderList()};row.onclick=()=>edit(q)})}
  function grow(x){x.style.height='auto';x.style.height=Math.min(Math.max(x.scrollHeight,96),420)+'px'}
  function edit(q){const opts=q.options||['','','',''];$b('#bankQuestionEditBody').innerHTML=`<div class="detail"><div class="eyebrow">REVISAR PREGUNTA ${q.number}</div><h2>Banco de preguntas</h2><div class="bankEditorGrid"><label class="fieldLabel wide">Enunciado<textarea id="bqStem" class="stemArea">${esc(q.stem||'')}</textarea></label>${[0,1,2,3].map(i=>`<label class="fieldLabel">Alternativa ${String.fromCharCode(65+i)}<textarea id="bqOpt${i}">${esc(opts[i]||'')}</textarea></label>`).join('')}<label class="fieldLabel">Correcta<select id="bqCorrect"><option value="">Sin detectar</option>${[0,1,2,3].map(i=>`<option value="${i}" ${q.correct_index===i?'selected':''}>${String.fromCharCode(65+i)}</option>`).join('')}</select></label><label class="fieldLabel">Especialidad<input id="bqSpecialty" value="${esc(q.specialty||'')}"></label><label class="fieldLabel">Tema<input id="bqTopic" value="${esc(q.topic||'')}"></label><label class="fieldLabel">Subtema<input id="bqSubtopic" value="${esc(q.subtopic||'')}"></label><label class="fieldLabel wide">Explicación<textarea id="bqExplanation" class="explainArea">${esc(q.explanation||'')}</textarea></label></div><div class="actions"><button id="bqCancel" class="secondary">Cancelar</button><button id="bqSave" class="primary">Guardar cambios</button></div></div>`;$$b('#bankQuestionEditBody textarea').forEach(x=>{grow(x);x.oninput=()=>grow(x)});$b('#bqCancel').onclick=()=>$b('#bankQuestionEditDialog').close();$b('#bqSave').onclick=()=>{q.stem=$b('#bqStem').value.trim();q.options=[0,1,2,3].map(i=>$b('#bqOpt'+i).value.trim());q.correct_index=$b('#bqCorrect').value===''?null:+$b('#bqCorrect').value;q.specialty=$b('#bqSpecialty').value.trim()||'Sin clasificar';q.topic=$b('#bqTopic').value.trim()||'General';q.subtopic=$b('#bqSubtopic').value.trim()||null;q.explanation=$b('#bqExplanation').value.trim();$b('#bankQuestionEditDialog').close();render()};$b('#bankQuestionEditDialog').showModal()}
  async function analyze(){if(st.analyzing)return;st.analyzing=true;st.questions=[];st.images.forEach(x=>URL.revokeObjectURL(x.url));st.images=new Map();showProg(true);setProg(1,'Preparando');$b('#bankAnalyzeBtn').disabled=true;try{await loadTaxonomy();if(st.mode==='single'){const f=$b('#bankSinglePdf').files[0],im=$b('#bankSingleImagesPdf').files[0];if(!f)throw new Error('Selecciona el PDF completo.');st.sourceKind='bank_pdf_single';const l=await extractLines(f,4,50),m=blocks(l),nums=[...m.keys()].sort((a,b)=>a-b);for(const n of nums){const base=merge([m.get(n)],n);if(!base)continue;const a=bestA(m.get(n)),q={...base,correct_index:a.correct_index,explanation:a.explanation,specialty:'Sin clasificar',topic:'General',subtopic:null,section:null};q.specialty=inferSpecialty(q);Object.assign(q,inferTopic(q,q.specialty));st.questions.push(q)}if(im)st.images=await extractImages(im)}else if(st.mode==='separate'){const qf=$b('#bankQuestionsPdf').files[0],af=$b('#bankAnswersPdf').files[0],im=$b('#bankImagesPdf').files[0];if(!qf&&!af)throw new Error('Selecciona el PDF de preguntas y/o claves.');st.sourceKind='bank_pdf_separate';const ql=qf?await extractLines(qf,3,25):[],al=af?await extractLines(af,28,28):[],qm=blocks(ql),am=blocks(al),nums=[...new Set([...qm.keys(),...am.keys()])].sort((a,b)=>a-b);for(const n of nums){const base=merge([qm.get(n),am.get(n)],n);if(!base)continue;const a=bestA(am.get(n)?.length?am.get(n):qm.get(n)),q={...base,correct_index:a.correct_index,explanation:a.explanation,specialty:'Sin clasificar',topic:'General',subtopic:null,section:null};q.specialty=inferSpecialty(q);Object.assign(q,inferTopic(q,q.specialty));st.questions.push(q)}if(im)st.images=await extractImages(im)}else{const f=$b('#bankRemnoteFile').files[0],mds=await loadRemnote(f),cards=[];for(const md of mds){const r=parseMarkdown(md.text,md.name);cards.push(...r.cards.filter(c=>c.type==='multiple_choice'))}const unique=dedupe(cards).unique;st.sourceKind='bank_remnote';let n=0;for(const c of unique){n++;const resolved=typeof resolveRemnoteMcqOptions==='function'?resolveRemnoteMcqOptions(c.options||[]):null,rawOpts=resolved?.options||(c.options||[]),opts=rawOpts.map(o=>typeof o==='string'?o:o.text||''),ci=resolved?.correct_index??rawOpts.findIndex(o=>o.correct),ex=resolved?.explanation||(rawOpts.find(o=>o.correct)?.extra||c.explanation||[]);st.questions.push({number:n,native_uid:c.uid,classification_origin:c.classification_origin,stem:scrub(c.front||''),options:opts.slice(0,4).map(scrub),correct_index:ci>=0&&ci<4?ci:null,explanation:scrub(Array.isArray(ex)?ex.join('\n'):String(ex||'')),specialty:c.specialty||'Sin clasificar',topic:c.topic||'General',subtopic:c.subtopic||null,section:c.section||null,image_number:null,correct_inferred_by:resolved?.method||c.correct_inferred_by||null})}}
      if(st.questions.length<1)throw new Error('No se detectaron preguntas.');const name=($b('#bankName').value.trim()||'Banco de preguntas');$b('#bankName').value=name;await existing(name);classifyStatuses(name);setProg(96,'Preparando revisión');$b('#bankSetup').classList.add('hidden');$b('#bankReview').classList.remove('hidden');render();setProg(100,`Listo · ${st.questions.length} preguntas`);setTimeout(()=>showProg(false),1000)}catch(e){console.error(e);alert('No se pudo analizar el banco: '+(e.message||e));showProg(false)}finally{st.analyzing=false;$b('#bankAnalyzeBtn').disabled=false}}
  function missingCol(err){const m=String(err?.message||err||'').match(/Could not find the ['"]([^'"]+)['"] column of ['"]?questions/i)||String(err?.message||'').match(/column ['"]?questions\.([^'"\s]+)['"]? does not exist/i);return m?.[1]||null}
  async function writeCompat(row,id){const p={...row};for(let i=0;i<20;i++){let error;if(id)({error}=await sb.from('questions').update(p).eq('id',id));else({error}=await sb.from('questions').upsert(p,{onConflict:'source_uid'}));if(!error)return;const c=missingCol(error);if(c&&c in p){delete p[c];continue}throw error}throw new Error('No se pudo adaptar el banco al esquema de questions.')}
  async function publish(){if(!cloudMode||!sb){alert('Conecta Supabase e inicia sesión como admin.');return}const sel=st.questions.filter(q=>st.selected.has(q.source_uid)&&q.status_import!=='unchanged');if(!sel.length){alert('No hay preguntas seleccionadas para publicar.');return}const bad=sel.filter(q=>q.correct_index==null||q.options.filter(Boolean).length<4);if(bad.length&&!confirm(`${bad.length} preguntas tienen problemas de alternativas o respuesta. Se publicarán como borrador. ¿Continuar?`))return;const name=$b('#bankName').value.trim()||'Banco de preguntas',year=+$b('#bankYear').value||null;$b('#bankPublishBtn').disabled=true;showProg(true);setProg(1,'Preparando publicación');try{let imp=null;try{const r=await sb.from('question_imports').insert({name:`Banco: ${name}`,source_kind:st.sourceKind,status:'processing',counts:{detected:st.questions.length,selected:sel.length,images:st.images.size},created_by:cloudUser.id}).select().single();if(!r.error)imp=r.data}catch{}
      const imagePaths=new Map(),needed=[...new Set(sel.map(q=>q.image_number).filter(Boolean))];let idone=0;for(const n of needed){const im=st.images.get(n);if(im){const path=`banks/${slug(name)}/imagen-${String(n).padStart(3,'0')}.jpg`,r=await sb.storage.from('question-images').upload(path,im.blob,{contentType:'image/jpeg',upsert:true});if(r.error)throw r.error;imagePaths.set(n,path)}idone++;setProg(5+20*(idone/Math.max(1,needed.length)),`Subiendo imágenes ${idone}/${needed.length}`)}let done=0;for(const q of sel){const row={source_uid:q.source_uid,source_number:q.number,image_path:imagePaths.get(q.image_number)||st.existing.get(q.source_uid)?.image_path||null,specialty:q.specialty||'Sin clasificar',topic:q.topic||'General',subtopic:q.subtopic||null,section:q.section||null,stem:q.stem,options:q.options,correct_index:q.correct_index??0,explanation:q.explanation||null,year,source:`Banco: ${name}`,status:(q.correct_index==null||q.options.filter(Boolean).length<4)?'draft':'published',import_id:imp?.id||null,updated_at:new Date().toISOString()};await writeCompat(row,q.db_id);done++;setProg(27+70*(done/sel.length),`Publicando ${done}/${sel.length}`)}if(imp)await sb.from('question_imports').update({status:'published',published_at:new Date().toISOString(),counts:{detected:st.questions.length,published:sel.length,new:sel.filter(q=>q.status_import==='new').length,modified:sel.filter(q=>q.status_import==='modified').length,draft:sel.filter(q=>q.correct_index==null||q.options.filter(Boolean).length<4).length,images:imagePaths.size}}).eq('id',imp.id);setProg(100,'Completado');alert(`Banco publicado: ${sel.length} preguntas. Ya están disponibles en Banqueo.`);await existing(name);classifyStatuses(name);render();setTimeout(()=>showProg(false),1200)}catch(e){console.error(e);alert('No se pudo publicar el banco: '+(e.message||e))}finally{$b('#bankPublishBtn').disabled=false}}
  function reset(){st.images.forEach(x=>URL.revokeObjectURL(x.url));st.questions=[];st.images=new Map();st.selected.clear();$b('#bankReview').classList.add('hidden');$b('#bankSetup').classList.remove('hidden');['bankSinglePdf','bankSingleImagesPdf','bankQuestionsPdf','bankAnswersPdf','bankImagesPdf','bankRemnoteFile'].forEach(id=>{const x=$b('#'+id);if(x)x.value=''});showProg(false)}
  function mode(m){if(m==='excel')return;st.mode=m;$$b('#bankSourceTabs .tab').forEach(x=>x.classList.toggle('active',x.dataset.mode===m));['single','separate','remnote'].forEach(x=>$b('#bankMode'+x[0].toUpperCase()+x.slice(1)).classList.toggle('hidden',x!==m));$b('#bankModeHelp').textContent={single:'Un PDF con preguntas y respuestas/comentarios en el mismo archivo.',separate:'Un PDF de preguntas + un PDF de claves/comentarios; imágenes opcionales.',remnote:'ZIP o Markdown de RemNote; solo flashcards de opción múltiple. NEXMIR identifica como correcta la alternativa con explicación hija; si no existe, usa la primera como respaldo.'}[m]}
  function init(){const nav=$b('[data-view="bankimport"]');if(nav)nav.addEventListener('click',()=>{});$b('#bankSourceTabs').onclick=ev=>{const b=ev.target.closest('.tab');if(b&&!b.disabled)mode(b.dataset.mode)};mode('single');$b('#bankAnalyzeBtn').onclick=analyze;$b('#bankPublishBtn').onclick=publish;$b('#bankResetBtn').onclick=reset;$b('#bankTabs').onclick=ev=>{if(!ev.target.matches('.tab'))return;$$b('#bankTabs .tab').forEach(x=>x.classList.remove('active'));ev.target.classList.add('active');st.filter=ev.target.dataset.filter;renderList()};$b('#bankSearch').oninput=renderList;$b('#bankSelectVisible').onchange=ev=>{for(const q of filtered()){if(q.status_import==='unchanged')continue;ev.target.checked?st.selected.add(q.source_uid):st.selected.delete(q.source_uid)}renderList()};$b('#bankQuestionEditClose').onclick=()=>$b('#bankQuestionEditDialog').close();$b('#bankName').onchange=async()=>{if(!st.questions.length)return;await existing($b('#bankName').value.trim()||'Banco de preguntas');classifyStatuses($b('#bankName').value.trim()||'Banco de preguntas');render()}}
  init();
})();
