/* NEXMIR V4.8 · Gestor de simulacros publicados */
(() => {
  const st={groups:[],imports:[],query:'',status:'all',active:null};
  const qsel=s=>document.querySelector(s), qall=s=>[...document.querySelectorAll(s)];
  const e=s=>esc(String(s??''));
  const slug=s=>String(s||'simulacro').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9ñ]+/g,'-').replace(/ñ/g,'n').replace(/^-|-$/g,'')||'simulacro';
  function issueReasons(q){const r=[],opts=Array.isArray(q.options)?q.options:[];if(opts.filter(x=>String(x||'').trim()).length<4)r.push('alternativas');if(!(Number.isInteger(q.correct_index)&&q.correct_index>=0&&q.correct_index<opts.length))r.push('respuesta');if(!String(q.explanation||'').trim())r.push('explicación');return r}
  function examStatus(rows){const ss=new Set(rows.map(x=>x.status||'published'));if(ss.size===1)return [...ss][0];if(ss.has('draft'))return'draft';return'mixed'}
  function latestDate(rows,imp){const vals=[imp?.published_at,imp?.created_at,...rows.map(x=>x.updated_at||x.created_at)].filter(Boolean).map(Date.parse).filter(Number.isFinite);return vals.length?new Date(Math.max(...vals)).toISOString():null}
  async function load(){
    const empty=qsel('#simMgrEmpty'),tbody=qsel('#simMgrTableBody');if(!tbody)return;
    if(!cloudMode||!sb){tbody.innerHTML='';empty.classList.remove('hidden');empty.textContent='Conecta Supabase e inicia sesión como admin para gestionar simulacros.';return}
    tbody.innerHTML='<tr><td colspan="8" class="muted">Cargando simulacros…</td></tr>';
    let rows=[];try{rows=await fetchAllPages(()=>sb.from('questions').select('*').not('source_exam','is',null).order('source_exam').order('source_number'))}catch(error){tbody.innerHTML=`<tr><td colspan="8" class="muted">${e(error.message)}</td></tr>`;return}
    let imports=[];try{const r=await sb.from('question_imports').select('*').order('created_at',{ascending:false});if(!r.error)imports=r.data||[]}catch{}
    st.imports=imports;
    const mp=new Map();for(const q of rows||[]){const name=String(q.source_exam||'').trim();if(!name)continue;(mp.get(name)||mp.set(name,[]).get(name)).push(q)}
    st.groups=[...mp.entries()].map(([name,qs])=>{const imp=imports.find(x=>x.name===name);return{name,qs:qs.sort((a,b)=>(+a.source_number||0)-(+b.source_number||0)),year:qs.find(x=>x.year)?.year||null,images:qs.filter(x=>x.image_path).length,problems:qs.filter(x=>issueReasons(x).length).length,status:examStatus(qs),date:latestDate(qs,imp)}}).sort((a,b)=>a.name.localeCompare(b.name,'es'));
    render();
  }
  function filtered(){const term=(qsel('#simMgrSearch')?.value||'').trim().toLowerCase(),status=qsel('#simMgrStatus')?.value||'all';return st.groups.filter(g=>(status==='all'||g.status===status)&&( !term || `${g.name} ${g.year||''}`.toLowerCase().includes(term)))}
  function render(){
    const tbody=qsel('#simMgrTableBody'),empty=qsel('#simMgrEmpty');if(!tbody)return;const arr=filtered();
    const total=st.groups.length,pub=st.groups.filter(x=>x.status==='published').length,prob=st.groups.reduce((n,x)=>n+x.problems,0),questions=st.groups.reduce((n,x)=>n+x.qs.length,0);
    qsel('#simMgrStats').innerHTML=`<div class="stat"><div class="num">${total}</div><div class="label">Simulacros</div></div><div class="stat"><div class="num">${questions}</div><div class="label">Preguntas</div></div><div class="stat"><div class="num">${pub}</div><div class="label">Publicados</div></div><div class="stat"><div class="num">${prob}</div><div class="label">Problemas</div></div>`;
    if(!arr.length){tbody.innerHTML='';empty.classList.remove('hidden');empty.textContent=st.groups.length?'No hay simulacros con esos filtros.':'No hay simulacros publicados todavía.';return}empty.classList.add('hidden');
    tbody.innerHTML=arr.map(g=>`<tr data-exam="${e(g.name)}"><td><strong>${e(g.name)}</strong></td><td>${e(g.year||'—')}</td><td>${g.qs.length}</td><td>${g.images}</td><td>${g.problems?`<span class="statusPill draft">${g.problems}</span>`:'0'}</td><td>${g.date?new Date(g.date).toLocaleString():'—'}</td><td><span class="statusPill ${e(g.status)}">${({published:'Publicado',archived:'Archivado',draft:'Con borradores',mixed:'Mixto'}[g.status]||e(g.status))}</span></td><td><div class="actions"><button class="secondary sm-open">Preguntas</button><button class="secondary sm-rename">Renombrar</button><button class="secondary sm-archive">${g.status==='archived'?'Republicar':'Archivar'}</button><button class="secondary sm-copy">Duplicar</button><button class="secondary danger sm-delete">Eliminar</button></div></td></tr>`).join('');
    qall('#simMgrTableBody tr').forEach(tr=>{const g=st.groups.find(x=>x.name===tr.dataset.exam);tr.querySelector('.sm-open').onclick=()=>openExam(g);tr.querySelector('.sm-rename').onclick=()=>renameExam(g);tr.querySelector('.sm-archive').onclick=()=>g.status==='archived'?republish(g):archive(g);tr.querySelector('.sm-copy').onclick=()=>duplicate(g);tr.querySelector('.sm-delete').onclick=()=>removeExam(g)});
  }
  function openExam(g){st.active=g;const body=qsel('#simManagerBody');body.innerHTML=`<div class="detail"><div class="eyebrow">GESTOR DE SIMULACROS</div><h2>${e(g.name)}</h2><div class="managerSummary"><div><strong>${g.qs.length}</strong><span>Preguntas</span></div><div><strong>${g.images}</strong><span>Con imagen</span></div><div><strong>${g.problems}</strong><span>Con problemas</span></div><div><strong>${e(g.year||'—')}</strong><span>Año</span></div></div><div class="managerToolbar"><input id="smQuestionSearch" type="search" placeholder="Buscar número, enunciado o tema…"><button id="smCloseExam" class="secondary">Cerrar</button></div><div id="smQuestionList" class="managerQuestionList"></div></div>`;qsel('#smCloseExam').onclick=()=>qsel('#simManagerDialog').close();qsel('#smQuestionSearch').oninput=()=>renderExamQuestions(g);renderExamQuestions(g);qsel('#simManagerDialog').showModal()}
  function renderExamQuestions(g){const box=qsel('#smQuestionList');if(!box)return;const term=(qsel('#smQuestionSearch')?.value||'').toLowerCase();const arr=g.qs.filter(q=>!term||`${q.source_number||''} ${q.stem||''} ${q.specialty||''} ${q.topic||''}`.toLowerCase().includes(term));box.innerHTML=arr.map(q=>`<div class="managerQuestion"><div class="qnum">${q.source_number??'—'}</div><div><div class="qtext">${e(q.stem||'')}</div><div class="qmeta">${e(q.specialty||'Sin clasificar')} › ${e(q.topic||'General')}${issueReasons(q).length?` · ⚠ ${issueReasons(q).join(', ')}`:''}</div></div><div class="actions"><button class="secondary sm-q-edit" data-id="${e(q.id)}">Editar</button></div></div>`).join('')||'<div class="empty">No hay coincidencias.</div>';qall('.sm-q-edit',box).forEach(b=>b.onclick=()=>editQuestion(g,b.dataset.id))}
  function autoGrow(el){el.style.height='auto';el.style.height=Math.min(Math.max(el.scrollHeight,92),420)+'px'}
  function editQuestion(g,id){const q=g.qs.find(x=>String(x.id)===String(id));if(!q)return;const opts=Array.isArray(q.options)?q.options:['','','',''];const body=qsel('#simManagerBody');body.innerHTML=`<div class="detail"><div class="eyebrow">EDITAR PREGUNTA ${e(q.source_number||'')}</div><h2>${e(g.name)}</h2><div class="bankEditorGrid"><label class="fieldLabel wide">Enunciado<textarea id="smStem" class="stemArea">${e(q.stem||'')}</textarea></label>${[0,1,2,3].map(i=>`<label class="fieldLabel">Alternativa ${String.fromCharCode(65+i)}<textarea id="smOpt${i}">${e(opts[i]||'')}</textarea></label>`).join('')}<label class="fieldLabel">Respuesta correcta<select id="smCorrect"><option value="">Sin detectar</option>${[0,1,2,3].map(i=>`<option value="${i}" ${q.correct_index===i?'selected':''}>${String.fromCharCode(65+i)}</option>`).join('')}</select></label><label class="fieldLabel">Especialidad<input id="smSpecialty" value="${e(q.specialty||'')}"></label><label class="fieldLabel">Tema<input id="smTopic" value="${e(q.topic||'')}"></label><label class="fieldLabel">Subtema<input id="smSubtopic" value="${e(q.subtopic||'')}"></label><label class="fieldLabel wide">Explicación<textarea id="smExplanation" class="explainArea">${e(q.explanation||'')}</textarea></label></div><div class="actions"><button id="smBack" class="secondary">← Volver</button><button id="smSave" class="primary">Guardar cambios</button></div></div>`;qall('#simManagerBody textarea').forEach(t=>{autoGrow(t);t.addEventListener('input',()=>autoGrow(t))});qsel('#smBack').onclick=()=>openExam(st.groups.find(x=>x.name===g.name)||g);qsel('#smSave').onclick=async()=>{const patch={stem:qsel('#smStem').value.trim(),options:[0,1,2,3].map(i=>qsel('#smOpt'+i).value.trim()),correct_index:qsel('#smCorrect').value===''?null:+qsel('#smCorrect').value,explanation:qsel('#smExplanation').value.trim()||null,specialty:qsel('#smSpecialty').value.trim()||'Sin clasificar',topic:qsel('#smTopic').value.trim()||'General',subtopic:qsel('#smSubtopic').value.trim()||null,updated_at:new Date().toISOString()};const {error}=await sb.from('questions').update(patch).eq('id',q.id);if(error){alert(error.message);return}Object.assign(q,patch);alert('Pregunta actualizada.');await load();const ng=st.groups.find(x=>x.name===g.name);openExam(ng||g)}}
  async function renameExam(g){const name=prompt('Nuevo nombre del simulacro:',g.name)?.trim();if(!name||name===g.name)return;if(st.groups.some(x=>x.name.toLowerCase()===name.toLowerCase())){alert('Ya existe un simulacro con ese nombre.');return}if(!confirm(`¿Renombrar “${g.name}” como “${name}”?`))return;let i=0;for(const q of g.qs){const patch={source_exam:name};if(Object.prototype.hasOwnProperty.call(q,'source_uid')&&q.source_uid)patch.source_uid=`sim:${slug(name)}:q${q.source_number||++i}`;const {error}=await sb.from('questions').update(patch).eq('id',q.id);if(error){alert('No se pudo renombrar: '+error.message);return}}alert('Simulacro renombrado.');await load()}
  async function archive(g){if(!confirm(`¿Archivar “${g.name}”? Dejará de aparecer a los alumnos, pero no se borrará.`))return;const {error}=await sb.from('questions').update({status:'archived',updated_at:new Date().toISOString()}).eq('source_exam',g.name);if(error){alert(error.message);return}await load()}
  async function republish(g){if(!confirm(`¿Republicar “${g.name}”?`))return;const {error}=await sb.from('questions').update({status:'published',updated_at:new Date().toISOString()}).eq('source_exam',g.name);if(error){alert(error.message);return}await load()}
  async function duplicate(g){const name=prompt('Nombre del simulacro duplicado:',`${g.name} - copia`)?.trim();if(!name)return;if(st.groups.some(x=>x.name.toLowerCase()===name.toLowerCase())){alert('Ya existe un simulacro con ese nombre.');return}if(!confirm(`Se crearán ${g.qs.length} preguntas nuevas bajo “${name}”. ¿Continuar?`))return;let done=0;for(const src of g.qs){const row={...src};delete row.id;delete row.created_at;delete row.updated_at;row.source_exam=name;row.status='published';row.import_id=null;if('source_uid'in row)row.source_uid=`sim:${slug(name)}:q${src.source_number||done+1}`;const {error}=await sb.from('questions').insert(row);if(error){alert(`Error al duplicar en pregunta ${src.source_number||done+1}: ${error.message}`);return}done++}alert(`Duplicado creado: ${done} preguntas.`);await load()}
  async function removeExam(g){const typed=prompt(`ELIMINAR borra las ${g.qs.length} preguntas de “${g.name}”.\nPara confirmar escribe exactamente el nombre del simulacro:`);if(typed!==g.name){if(typed!==null)alert('El nombre no coincide. No se eliminó nada.');return}const {error}=await sb.from('questions').delete().eq('source_exam',g.name);if(error){alert(error.message);return}alert('Simulacro eliminado de la base. Las imágenes físicas se conservan por seguridad para no romper posibles duplicados.');await load()}
  function init(){const nav=qsel('[data-view="simmanager"]');if(nav)nav.addEventListener('click',()=>setTimeout(load,0));qsel('#simMgrRefresh')?.addEventListener('click',load);qsel('#simMgrSearch')?.addEventListener('input',render);qsel('#simMgrStatus')?.addEventListener('change',render);qsel('#simManagerClose')?.addEventListener('click',()=>qsel('#simManagerDialog').close())}
  window.NexmirSimulationsBulk={all:filtered,visible:filtered,selector:'#simMgrTableBody tr',host:'#simMgrTableBody',key:g=>g.name,canWrite:()=>cloudMode&&cloudRole==='admin',remove:async g=>{const {error}=await sb.from('questions').delete().eq('source_exam',g.name);if(error)throw error;st.groups=st.groups.filter(x=>x.name!==g.name)},refresh:load};
  init();window.refreshSimulationManager=load;
})();
