/* NEXMIR V5.1.19 · usuarios, planes, roles y dispositivo */
(() => {
 const st={rows:[]}; const $=s=>document.querySelector(s); const esc2=s=>esc(String(s??''));
 async function load(){const b=$('#usersBody');if(!b)return;if(!cloudMode||!sb){b.innerHTML='<tr><td colspan="6" class="muted">Conecta Supabase.</td></tr>';return}b.innerHTML='<tr><td colspan="6" class="muted">Cargando usuarios…</td></tr>';let data=[];try{data=await fetchAllPages(()=>sb.from('profiles').select('*').order('updated_at',{ascending:false}))}catch(error){b.innerHTML=`<tr><td colspan="6" class="muted">${esc2(error.message)}</td></tr>`;return}st.rows=data||[];render()}
 function filtered(){const term=($('#usersSearch')?.value||'').toLowerCase(),plan=$('#usersPlan')?.value||'all',role=$('#usersRole')?.value||'all';return st.rows.filter(x=>(plan==='all'||(x.plan||'free')===plan)&&(role==='all'||(x.role||'user')===role)&&(!term||`${x.display_name||''} ${x.email||''} ${x.goal_specialty||''}`.toLowerCase().includes(term)))}
 function render(){const arr=filtered(),b=$('#usersBody'),empty=$('#usersEmpty');if(!arr.length){b.innerHTML='';empty.classList.remove('hidden');return}empty.classList.add('hidden');b.innerHTML=arr.map(x=>`<tr><td><strong>${esc2(x.display_name||'Sin nombre')}</strong><div class="muted">${esc2(x.email||x.id)}</div></td><td><select class="usrPlan" data-id="${esc2(x.id)}"><option value="free" ${(x.plan||'free')==='free'?'selected':''}>Free</option><option value="pro" ${x.plan==='pro'?'selected':''}>Pro</option></select></td><td><select class="usrRole" data-id="${esc2(x.id)}"><option value="user" ${(x.role||'user')==='user'?'selected':''}>user</option><option value="moderator" ${x.role==='moderator'?'selected':''}>moderator</option><option value="admin" ${x.role==='admin'?'selected':''}>admin</option></select></td><td><span>${esc2(x.active_device_label||'Sin vincular')}</span></td><td>${esc2(x.goal_specialty||'—')}<div class="muted">${x.target_number?'Nº < '+esc2(x.target_number):''}</div></td><td><div class="actions"><button class="secondary usrSave" data-id="${esc2(x.id)}">Guardar</button><button class="secondary usrReset" data-id="${esc2(x.id)}">Reset dispositivo</button></div></td></tr>`).join('');[...b.querySelectorAll('.usrSave')].forEach(btn=>btn.onclick=()=>save(btn.dataset.id));[...b.querySelectorAll('.usrReset')].forEach(btn=>btn.onclick=()=>reset(btn.dataset.id))}
 async function save(id){const row=st.rows.find(x=>String(x.id)===String(id)),tr=[...$('#usersBody').rows].find(r=>r.querySelector('.usrSave')?.dataset.id===id);if(!row||!tr)return;const plan=tr.querySelector('.usrPlan').value,role=tr.querySelector('.usrRole').value,button=tr.querySelector('.usrSave');button.disabled=true;button.textContent='Guardando…';try{const {data,error}=await sb.from('profiles').update({plan,role,updated_at:new Date().toISOString()}).eq('id',id).select('id,plan,role,updated_at').single();if(error)throw error;if(!data||data.plan!==plan||data.role!==role)throw new Error('Supabase no confirmó el cambio de plan y rol.');Object.assign(row,data);alert(`Usuario actualizado: plan ${data.plan.toUpperCase()} · rol ${data.role}`)}catch(error){alert(error.message||'No se pudo actualizar el usuario');await load()}finally{button.disabled=false;button.textContent='Guardar'}}
 async function reset(id){if(!confirm('¿Desvincular el dispositivo actual de este usuario?'))return;const {error}=await sb.from('profiles').update({active_device_id:null,active_device_label:null,device_updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);await load()}
 function init(){document.querySelector('[data-view="users"]')?.addEventListener('click',()=>setTimeout(load,0));$('#usersRefresh').onclick=load;['usersSearch','usersPlan','usersRole'].forEach(id=>{$('#'+id).oninput=render;$('#'+id).onchange=render})}
 init();
})();
